### ISSUE TITLE
Note names with hyphens are not processed

### ISSUE THREAD

**Issue by ghost** [davidnalesnik/lilypond-roman-numeral-tool#1]
```
\version "2.18"

\include "roman_numeral_analysis_tool.ily"

{
  cis''1-\markup \keyIndication { c-sharp }
  cis''1-\markup \rN { c-sharp }
}
```

Is rendered as

![note-names](https://cloud.githubusercontent.com/assets/12159469/11768751/0dc198dc-a1ce-11e5-93b3-7eb80d488db8.png)

I solved this issue by replacing [line 142](https://github.com/davidnalesnik/lilypond-roman-numeral-tool/blob/cc9cf37284ea07214139384fc047f25940bffae4/roman_numeral_analysis_tool.ily#L142) with

```
   (let ((lowercased (string-regexp-substitute "-" "" (format #f "~(~a~)" str))))
```

(It's a dirty hack, I know.)

**Comment by davidnalesnik** [comment]
When I run the code as-is on a current development release, I get this:

![image](https://cloud.githubusercontent.com/assets/5365752/11768819/25feef06-a19e-11e5-98d6-8a53359a3b11.png)

I believe David Kastrup modified the note names in a recent patch.  I forgot about this (as I use the Dutch names everywhere else).  Sorry--I realize that the version statement is for stable;  I assumed I wasn't relying on new functionality, but I assumed wrong.

Your line will raise an error on recent versions.  I think the best course of action would be to add  the unhyphenated names to the english-note-names variable.  I'll get on that soon.  Thanks for pointing it out.

Here's the list on my system (which reminds me that I need to filter out the quarter-tone accidentals):

(cff ctqf cf cqf c cqs cs ctqs css cx dff dtqf df dqf d dqs ds dtqs dss dx eff etqf ef eqf e eqs es etqs ess ex fff ftqf ff fqf f fqs fs ftqs fss fx gff gtqf gf gqf g gqs gs gtqs gss gx aff atqf af aqf a aqs as atqs ass ax bff btqf bf bqf b bqs bs btqs bss bx c-flatflat c-flat c-natural c-sharp c-sharpsharp d-flatflat d-flat d-natural d-sharp d-sharpsharp e-flatflat e-flat e-natural e-sharp e-sharpsharp f-flatflat f-flat f-natural f-sharp f-sharpsharp g-flatflat g-flat g-natural g-sharp g-sharpsharp a-flatflat a-flat a-natural a-sharp a-sharpsharp b-flatflat b-flat b-natural b-sharp b-sharpsharp)

David

**Comment by ghost** [comment]
Here's the output of `#(display english-note-names)` on my system:

```
(cflatflat cflat c csharp csharpsharp dflatflat dflat d dsharp dsharpsharp eflatflat eflat e esharp esharpsharp fflatflat fflat f fsharp fsharpsharp gflatflat gflat g gsharp gsharpsharp aflatflat aflat a asharp asharpsharp bflatflat bflat b bsharp bsharpsharp cff ctqf cf cqf c cqs cs ctqs css cx dff dtqf df dqf d dqs ds dtqs dss dx eff etqf ef eqf e eqs es etqs ess ex fff ftqf ff fqf f fqs fs ftqs fss fx gff gtqf gf gqf g gqs gs gtqs gss gx aff atqf af aqf a aqs as atqs ass ax bff btqf bf bqf b bqs bs btqs bss bx)
```

```
$ lilypond -v | head -n 1
GNU LilyPond 2.18.2
```

**Comment by davidnalesnik** [comment]
I realize now that this is actually just an issue of documentation.  If you are using versions older than 2.19.16, you would use the unhyphenated form, csharp instead of c-sharp.  (The code for \rN simply uses whatever note names are stored in a global variable in scm/define-note-names.scm,) 

I've added a note to README.md making this clear.

Thank you for alerting me to this problem!
