### ISSUE TITLE
Unbound variable: parse-figure-with-alteration

### ISSUE THREAD

**Issue by ghost** [davidnalesnik/lilypond-roman-numeral-tool#4]
`parse-figure-with-alteration` function was removed by d661b47 commit, but is still being used in `scaleDegree` markup command:

```
roman_numeral_analysis_tool.ily:485:24: Unbound variable: parse-figure-with-alteration
```

**Comment by davidnalesnik** [comment]
Fixed.  Thanks for finding this!
