### ISSUE TITLE
What is the license for this repository?

### ISSUE THREAD

**Issue by noteflakes** [davidnalesnik/lilypond-roman-numeral-tool#6]
Hi,

I'm would like to include your roman numerals code in a lilypond library I'm putting together, but I noticed there's no license information here. Could you add a license, just to make things clear regarding code reuse.

Thanks,
Sharon

**Comment by davidnalesnik** [comment]
I've been meaning to do this.  Thanks for reminding me--I'll get this up in
the next several days.

I'll probably just use the same license as LilyPond proper.

David

**Comment by davidnalesnik** [comment]
Added the MIT License.

**Comment by noteflakes** [comment]
Thanks, look here for the fork: https://github.com/noteflakes/lyp-roman-numerals

(If you want more info email me: ciconia at gmail dot com)
