### ISSUE TITLE
Adding Roman Numerals To Organ Scores

### ISSUE THREAD

**Issue by Yuna-She-They** [davidnalesnik/lilypond-roman-numeral-tool#8]
I'm having trouble adding the Roman Numerals to Organ scores for some reason, every time I Add a new voice it adds an additional staff and that's not what I want

**Comment by davidnalesnik** [comment]
Hi,

Could you add a very short example?

Thanks,
David

**Comment by Yuna-She-They** [comment]
um I'm working with phantom stuff in right now when working on the score Think of me I get an additional staff  when I use
    \new voice = "anaylize" {}
    \new Lyrics \with {
        \lyrics to "analize" {\left}
    }
when I don't use the new voice no additonal staff shows up but the roman numerals don't show up either

**Comment by davidnalesnik** [comment]
Hi,

The problem appears to lie with your LilyPond usage rather than the
Roman-numeral tool.

Corrected:

{  % missing
\new Voice = "analyze" {  } % Voice must be capitalized, analyze is not
spelled consistently
\new Lyrics \with { \lyricsto "analyze" \left } % lyricsto = one word, name
must match exactly
}

Not sure why you use the \with construction.  Why not

\new Lyrics \lyricsto "analyze" \left

Hope this helps--
David

**Comment by Yuna-She-They** [comment]
Thanks This will make my Music Theory classes a lot easer now that I can type them out

**Comment by Yuna-She-They** [comment]
Mabye I should look at the example again, I'm getthing this 3rd staff http://prntscr.com/kms1vp and I also have analysis = \lyricmode { \markup \rN { I } } but I'm still not getting the roman numarals, could you possibly include an example with panio and organ scores?

**Comment by davidnalesnik** [comment]
Hi,

If you include the LilyPond code that produced the four measures you
screenshot, I could probably fix it for you.

Best,
David

**Comment by Yuna-She-They** [comment]
analysis = \lyricmode {
  \override LyricText.self-alignment-X = #-0.6
  \markup \rN { I }
}

\score {
  <<
    \new PianoStaff \with {
      instrumentName = "Organ"
    } <<
      \new Staff = "right" \right
      \new Staff = "left" { \clef bass \left }
      \new Voice = "anaylize"
      \new Lyrics  \lyricsto "anaylize" {\analysis}
    >>
    \new Staff = "pedal" { \clef bass \pedal }
  >>
  \layout { }
}

I left out all the music

**Comment by davidnalesnik** [comment]
On Sat, Aug 25, 2018 at 11:37 AM Braber01 <notifications@github.com> wrote:

> analysis = \lyricmode {
> \override LyricText.self-alignment-X = #-0.6
> \markup \rN { I }
> }
>
> \score {
> <<
> \new PianoStaff \with {
> instrumentName = "Organ"
> } <<
> \new Staff = "right" \right
> \new Staff = "left" { \clef bass \left }
> \new Voice = "anaylize"
> \new Lyrics \lyricsto "anaylize" {\analysis}
> >>
> \new Staff = "pedal" { \clef bass \pedal }
>
> \layout { }
> }
>
> I left out all the music
>
I needed to add some so it would compile.

Here is what your code would look like corrected:

analysis = \lyricmode {
  \override LyricText.self-alignment-X = #-0.6
  \markup \rN { I }
}

\score {
  <<
    \new PianoStaff \with {
      instrumentName = "Organ"
    } <<
      \new Staff = "right" { c''1 }
      \new Staff = "left" <<
        \new Voice = "anaylize" {
          \clef bass c1
        }
        \new Lyrics \lyricsto "anaylize" { \analysis }
      >>
    >>
    \new Staff = "pedal" { \clef bass c, }
  >>
  \layout { }
}

The problems I'm seeing aren't issues with the roman-numeral tool--they're
questions about LilyPond usage.

Hope this helps.
David

**Comment by davidnalesnik** [comment]
The 3 ">" beginning lines should of course be ">>"  -- github has garbled my cut and paste.
